apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: clusterip-gw-agent
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: clusterip-gw-agent
subjects:
- kind: ServiceAccount
  name: clusterip-gw-agent
  namespace: kube-system
